# Generated by Django 3.2.7 on 2021-11-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=10, max_digits=12)),
                ('date', models.DateField()),
            ],
        ),
    ]
