# Generated by Django 3.2.9 on 2021-11-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
